version: '3.9'

services: 
  mongo-db: 
    container_name: mongo-db
    image: mongo
    env_file: 
      - .env
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_DB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_DB_PASS
    volumes: 
      - ./volumes/mongo:/data/db
    ports: 
      - '27017:27017'
    restart: always

  postgres-db:
    container_name: postgres-db
    image: postgres:16
    env_file:
      - .env
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
    volumes:
      - ./volumes/pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always

  mongo-express:
    container_name: mongo-express
    image: mongo-express
    env_file: 
      - .env
    environment: 
      - ME_CONFIG_MONGODB_ADMINUSERNAME=$MONGO_DB_USER
      - ME_CONFIG_MONGODB_ADMINPASSWORD=$MONGO_DB_PASS
      - ME_CONFIG_MONGODB_URL=$MONGO_DB_URL
      - ME_CONFIG_BASICAUTH_USERNAME=$MONGO_EXPRESS_USER
      - ME_CONFIG_BASICAUTH_PASSWORD=$MONGO_EXPRESS_PASS
    ports: 
      - '8081:8081'
    restart: always

  fas-bot: 
    container_name: fas-bot
    depends_on: 
      - mongo-db
      - postgres-db
    build: 
      context: .
      dockerfile: Dockerfile
    env_file: 
      - .env
    volumes: 
      - .:/app
      - /app/node_modules
    ports: 
      - '3000:3000'
    external_links: 
      - mongo-db
      - postgres-db
    command: yarn dev
    restart: always